### ISSUE TITLE
Compiler error with clang 20 on arm_depthwise_conv_wrapper_s8.c

### ISSUE THREAD

**Issue by jgoldstn** [ARM-software/CMSIS-NN#162]
While trying to compile with clang 20.0.0git, I ran into the following compiler error with warnings as errors enabled.

`arm_depthwise_conv_wrapper_s8.c:65:18: error: arithmetic on a pointer to void is a GNU extension [-Werror,-Wgnu-pointer-arith]`

This seems to be a valid warning as, while many compilers allow it, we really shouldn't be doing arithmetic on `void *` as it is not a valid target for pointer arithmetic.

**Comment by ArmRyan** [comment]
Closing since #163 has been merged.
